Try bash debugging traps

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -48,20 +48,33 @@ runs:
         # Do not set this as `GITHUB_ACTION_REF` due to a bug in the runner!
         GITHUB_ACTION_REF_COMMITISH: ${{ github.action_ref }}
       run: |
+        set -eE -o functrace
+        failure() {
+          local lineno=$1
+          local msg=$2
+          echo "Failed at $lineno: $msg"
+        }
+        trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
         CLEAN_COMMITISH=$(echo "${GITHUB_ACTION_REF_COMMITISH}" | sed 's/[^a-zA-Z0-9._-]*$//g')
         echo "commitish=${CLEAN_COMMITISH}" >> $GITHUB_OUTPUT
 
         # Check for format of either major version tag ("v1") or a standard SemVer tag ("v1.0.7")
+        echo 1
         VERSION_TAG=$(echo "${CLEAN_COMMITISH}" | grep -E '^v[0-9]+(\.[0-9]+\.[0-9]+)?$')
 
+        echo 2
         # If the commitish is a version tag, check if the tag actually exists
         if [[ $? -eq 0 ]]; then
+          echo 3
           echo "Using tag '${VERSION_TAG}' for commitish '${CLEAN_COMMITISH}'"
           echo "tag=${VERSION_TAG}" >> $GITHUB_OUTPUT
         elif [[ "${CLEAN_COMMITISH}" == "main" ]]; then
+          echo 4
           echo "Using tag 'latest' for commitish '${CLEAN_COMMITISH}'"
           echo "tag=latest" >> $GITHUB_OUTPUT
         else
+          echo 5
           echo "Using fallback tag '${FALLBACK_TAG}' for commitish '${CLEAN_COMMITISH}'"
           echo "tag=${FALLBACK_TAG}" >> $GITHUB_OUTPUT
         fi
